# Generated by Django 2.2.1 on 2019-07-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_auto_20190729_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='goods_store',
            field=models.CharField(max_length=32, verbose_name='商品店铺'),
        ),
    ]
