# Generated by Django 2.2.1 on 2019-07-29 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_address', models.ImageField(upload_to='store/images', verbose_name='图片地址')),
                ('img_description', models.TextField(max_length=32, verbose_name='图片描述')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Goods', verbose_name='商品id')),
            ],
        ),
    ]
