# Generated by Django 2.2.1 on 2019-07-26 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20190725_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storetype',
            old_name='type_descripiton',
            new_name='type_description',
        ),
    ]
